clc;
clear;
close all;

%% ===================== 第六章图表生成代码 =====================

fontName = 'Microsoft YaHei';

% 低饱和度配色
color_blue   = [0.55 0.67 0.82];
color_orange = [0.86 0.63 0.47];
color_green  = [0.58 0.72 0.62];
color_gray   = [0.86 0.86 0.86];
color_border = [0.35 0.35 0.35];

%% ===================== 表6-1：模型优缺点及改进方向汇总表（黑白版） =====================

figure('Color', 'w', 'Position', [100, 100, 1500, 850]);
axis off;

title('表6-1 模型优缺点及改进方向汇总表', ...
    'FontName', fontName, ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'Color', [0 0 0]);

headers = {'模型部分', '优点', '不足', '改进方向'};

data = {
    '线路潮流回归模型', ...
    '计算简单，拟合效果好，便于后续调用', ...
    '只能近似反映潮流关系，外推能力有限', ...
    '可改进为直流潮流模型或交流潮流模型';
    
    '阻塞费用模型', ...
    '能区分序内容量补偿和序外容量补偿，公平性较好', ...
    '未考虑启停成本、备用成本等因素', ...
    '加入机组运行成本和辅助服务成本';
    
    '市场出清模型', ...
    '符合分段报价和统一清算价规则', ...
    '未考虑备用容量和机组启停约束', ...
    '加入备用约束和多时段优化';
    
    '阻塞管理优化模型', ...
    '能兼顾线路安全和费用最小', ...
    '正常限值下可能无可行解', ...
    '引入安全裕度、需求响应和储能调节';
    
    '高负荷推广模型', ...
    '能分析负荷增加后的阻塞风险', ...
    '对负荷预测误差考虑不足', ...
    '可加入鲁棒优化或随机优化'
};

% 表格布局参数
left = 0.04;
bottom = 0.08;
tableW = 0.92;
tableH = 0.76;

nRows = size(data, 1) + 1;
nCols = 4;

colW = [0.18, 0.28, 0.25, 0.29] * tableW;
rowH = tableH / nRows;

xPos = left + [0, cumsum(colW(1:end-1))];

% 黑白灰配色
headerColor = [0.82 0.82 0.82];   % 表头浅灰
rowColor1   = [1 1 1];             % 白色
rowColor2   = [0.94 0.94 0.94];    % 浅灰
borderColor = [0 0 0];             % 黑色边框
textColor   = [0 0 0];             % 黑色文字

% 绘制表头
for c = 1:nCols
    
    annotation('textbox', [xPos(c), bottom + tableH - rowH, colW(c), rowH], ...
        'String', headers{c}, ...
        'FontName', fontName, ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'Color', textColor, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', headerColor, ...
        'EdgeColor', borderColor, ...
        'LineWidth', 1.2, ...
        'FitBoxToText', 'off');
    
end

% 绘制表格内容
for r = 1:size(data, 1)
    
    for c = 1:nCols
        
        if mod(r, 2) == 1
            bgColor = rowColor1;
        else
            bgColor = rowColor2;
        end
        
        annotation('textbox', [xPos(c), bottom + tableH - (r + 1) * rowH, colW(c), rowH], ...
            'String', data{r, c}, ...
            'FontName', fontName, ...
            'FontSize', 10.5, ...
            'Color', textColor, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'BackgroundColor', bgColor, ...
            'EdgeColor', borderColor, ...
            'LineWidth', 0.8, ...
            'FitBoxToText', 'off');
        
    end
    
end

exportgraphics(gcf, '表6-1_模型优缺点及改进方向汇总表_黑白版.png', 'Resolution', 300);
%% ===================== 图6-2：阻塞管理模型推广应用示意图 =====================

figure('Color', 'w', 'Position', [120, 120, 1100, 850]);
axis off;

title('图6-2 阻塞管理模型推广应用示意图', ...
    'FontName', fontName, ...
    'FontSize', 18, ...
    'FontWeight', 'bold');

boxText2 = {
    '历史运行数据\newline机组出力、线路潮流、负荷数据'
    '潮流关系建模\newline回归模型 / 直流潮流模型 / 交流潮流模型'
    '市场出清计算\newline分段报价、爬坡约束、负荷平衡'
    '线路安全校验\newline正常潮流限值、安全裕度限值'
    '阻塞管理优化\newline机组出力调整、储能调节、需求响应'
    '费用补偿与调度决策\newline阻塞费用计算、补偿分摊、调度方案输出'
};

n2 = length(boxText2);

x2 = 0.10;
w2 = 0.80;
h2 = 0.10;
yStart2 = 0.78;
gap2 = 0.035;

colors2 = {
    color_blue
    color_green
    color_orange
    color_gray
    color_green
    color_blue
};

for i = 1:n2
    
    y = yStart2 - (i - 1) * (h2 + gap2);
    
    annotation('textbox', [x2, y, w2, h2], ...
        'String', boxText2{i}, ...
        'FontName', fontName, ...
        'FontSize', 13, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', colors2{i}, ...
        'EdgeColor', color_border, ...
        'LineWidth', 1.2, ...
        'FitBoxToText', 'off');
    
    if i < n2
        annotation('arrow', ...
            [x2 + w2/2, x2 + w2/2], ...
            [y - 0.005, y - gap2 + 0.005], ...
            'Color', color_border, ...
            'LineWidth', 1.5);
    end
    
end

exportgraphics(gcf, '图6-2_阻塞管理模型推广应用示意图.png', 'Resolution', 300);


%% ===================== 表6-1：模型优缺点及改进方向汇总表 =====================

figure('Color', 'w', 'Position', [100, 100, 1500, 850]);
axis off;

title('表6-1 模型优缺点及改进方向汇总表', ...
    'FontName', fontName, ...
    'FontSize', 18, ...
    'FontWeight', 'bold');

headers = {'模型部分', '优点', '不足', '改进方向'};

data = {
    '线路潮流回归模型', ...
    '计算简单，拟合效果好，便于后续调用', ...
    '只能近似反映潮流关系，外推能力有限', ...
    '可改进为直流潮流模型或交流潮流模型';
    
    '阻塞费用模型', ...
    '能区分序内容量补偿和序外容量补偿，公平性较好', ...
    '未考虑启停成本、备用成本等因素', ...
    '加入机组运行成本和辅助服务成本';
    
    '市场出清模型', ...
    '符合分段报价和统一清算价规则', ...
    '未考虑备用容量和机组启停约束', ...
    '加入备用约束和多时段优化';
    
    '阻塞管理优化模型', ...
    '能兼顾线路安全和费用最小', ...
    '正常限值下可能无可行解', ...
    '引入安全裕度、需求响应和储能调节';
    
    '高负荷推广模型', ...
    '能分析负荷增加后的阻塞风险', ...
    '对负荷预测误差考虑不足', ...
    '可加入鲁棒优化或随机优化'
};

% 表格布局参数
left = 0.04;
bottom = 0.08;
tableW = 0.92;
tableH = 0.76;

nRows = size(data, 1) + 1;
nCols = 4;

colW = [0.18, 0.28, 0.25, 0.29] * tableW;
rowH = tableH / nRows;

xPos = left + [0, cumsum(colW(1:end-1))];

% 绘制表头
for c = 1:nCols
    
    annotation('textbox', [xPos(c), bottom + tableH - rowH, colW(c), rowH], ...
        'String', headers{c}, ...
        'FontName', fontName, ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'BackgroundColor', color_blue, ...
        'EdgeColor', color_border, ...
        'LineWidth', 1.2, ...
        'FitBoxToText', 'off');
    
end

% 绘制表格内容
for r = 1:size(data, 1)
    
    for c = 1:nCols
        
        if mod(r, 2) == 1
            bgColor = [0.97 0.97 0.97];
        else
            bgColor = [1 1 1];
        end
        
        annotation('textbox', [xPos(c), bottom + tableH - (r + 1) * rowH, colW(c), rowH], ...
            'String', data{r, c}, ...
            'FontName', fontName, ...
            'FontSize', 10.5, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'BackgroundColor', bgColor, ...
            'EdgeColor', color_border, ...
            'LineWidth', 0.8, ...
            'FitBoxToText', 'off');
        
    end
    
end

exportgraphics(gcf, '表6-1_模型优缺点及改进方向汇总表.png', 'Resolution', 300);

fprintf('第六章图片和表格已全部生成。\n');