function solution = solve_model(model)
%SOLVE_MODEL 使用 intlinprog 求解MILP

options = optimoptions('intlinprog', ...
    'Display', 'iter', ...
    'RelativeGapTolerance', 1e-5, ...
    'AbsoluteGapTolerance', 1e-6, ...
    'MaxTime', 600);

[x, fval, exitflag, output] = intlinprog( ...
    model.f, ...
    model.intcon, ...
    model.A, ...
    model.b, ...
    model.Aeq, ...
    model.beq, ...
    model.lb, ...
    model.ub, ...
    options);

if isempty(x)
    error('intlinprog 未返回可行解。');
end

solution.x = x;
solution.fval = fval;
solution.exitflag = exitflag;
solution.output = output;
solution.objectiveValue = -fval;

end
