%% 图2 一次反射光线追踪示意图
% 坐标系：
% x轴：水平方向，线光源方向
% y轴：车灯对称轴，指向正前方
% z轴：竖直方向

clear; clc; close all;

%% 1. 基本参数
R = 36;              % 车灯开口半径，mm
d = 21.6;            % 车灯深度，mm
f = R^2/(4*d);       % 焦距，mm
L = 8;               % 线光源长度，mm，可改成第一问最优长度

% 测试屏真实位置为 y = 25015 mm
% 为便于示意图显示，这里压缩显示为 y = 180 mm
screen_y_show = 180;

%% 2. 绘制抛物面 x^2 + z^2 = 60y
theta = linspace(0, 2*pi, 120);
r = linspace(0, R, 60);
[Theta, RR] = meshgrid(theta, r);

X = RR .* cos(Theta);
Z = RR .* sin(Theta);
Y = RR.^2 / (4*f);

figure('Color','w','Position',[100 100 1000 720]);
hold on; grid on; box on;

surf(X, Y, Z, ...
    'FaceColor',[0.70 0.85 1.00], ...
    'EdgeColor',[0.55 0.65 0.75], ...
    'FaceAlpha',0.45, ...
    'LineWidth',0.25);

%% 3. 绘制开口边界
theta_rim = linspace(0, 2*pi, 300);
x_rim = R*cos(theta_rim);
z_rim = R*sin(theta_rim);
y_rim = d*ones(size(theta_rim));

plot3(x_rim, y_rim, z_rim, ...
    'Color',[0.10 0.20 0.45], ...
    'LineWidth',1.8);

%% 4. 绘制焦点和线光源
F = [0, f, 0];

plot3(F(1), F(2), F(3), ...
    'ko', 'MarkerSize',7, 'MarkerFaceColor','k');

text(F(1)+2, F(2)+4, F(3)+3, ...
    'F', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'FontName','Microsoft YaHei');

% 线光源沿 x 轴方向
x_source = linspace(-L/2, L/2, 100);
y_source = f * ones(size(x_source));
z_source = zeros(size(x_source));

plot3(x_source, y_source, z_source, ...
    'r-', 'LineWidth',5);

text(0, f-9, -8, ...
    '线光源', ...
    'Color','r', ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei', ...
    'HorizontalAlignment','center');

%% 5. 绘制测试屏
screen_x_min = -55;
screen_x_max = 55;
screen_z_min = -45;
screen_z_max = 45;

screen_X = [screen_x_min screen_x_max screen_x_max screen_x_min];
screen_Y = screen_y_show * ones(1,4);
screen_Z = [screen_z_min screen_z_min screen_z_max screen_z_max];

patch(screen_X, screen_Y, screen_Z, ...
    [0.92 0.92 0.92], ...
    'FaceAlpha',0.35, ...
    'EdgeColor',[0.35 0.35 0.35], ...
    'LineWidth',1.2);

text(screen_x_min+3, screen_y_show+3, screen_z_max+4, ...
    '测试屏（示意压缩显示）', ...
    'FontSize',10, ...
    'FontName','Microsoft YaHei');

%% 6. 选取若干代表性光线
% 每一行表示一条光线：
% t_source：线光源上的位置
% r_reflect, theta_reflect：抛物面反射点参数

ray_data = [
   -3.5,  34,  0.15*pi;
   -2.0,  30,  0.40*pi;
    0.0,  36,  0.00*pi;
    0.0,  32, -0.35*pi;
    2.0,  30,  1.55*pi;
    3.5,  34,  1.85*pi
];

% 光线颜色
ray_color_in  = [0.10 0.35 0.80];   % 入射光线颜色
ray_color_out = [0.90 0.25 0.10];   % 反射光线颜色

for i = 1:size(ray_data,1)

    t = ray_data(i,1);
    rr = ray_data(i,2);
    th = ray_data(i,3);

    % 光源点 S
    S = [t, f, 0];

    % 抛物面反射点 P
    P = [rr*cos(th), rr^2/(4*f), rr*sin(th)];

    % 入射方向
    vi = P - S;

    % 法向量 n = (x, -30, z)
    n = [P(1), -2*f, P(3)];

    % 反射方向
    vr = vi - 2 * dot(vi,n) / dot(n,n) * n;

    % 保证反射方向朝向正 y 方向
    if vr(2) <= 0
        continue;
    end

    % 与测试屏 y = screen_y_show 的交点
    lambda = (screen_y_show - P(2)) / vr(2);
    Q = P + lambda * vr;

    % 画入射光线 S -> P
    plot3([S(1), P(1)], [S(2), P(2)], [S(3), P(3)], ...
        '-', ...
        'Color',ray_color_in, ...
        'LineWidth',1.5);

    % 画反射光线 P -> Q
    plot3([P(1), Q(1)], [P(2), Q(2)], [P(3), Q(3)], ...
        '-', ...
        'Color',ray_color_out, ...
        'LineWidth',1.8);

    % 标出反射点 P
    plot3(P(1), P(2), P(3), ...
        'ko', ...
        'MarkerSize',4, ...
        'MarkerFaceColor','k');

    % 标出测试屏落点 Q
    plot3(Q(1), Q(2), Q(3), ...
        'o', ...
        'MarkerSize',5, ...
        'MarkerFaceColor',ray_color_out, ...
        'MarkerEdgeColor',ray_color_out);
end

%% 7. 标注一个代表性反射点 P 和落点 Q
% 取第一条光线作为代表
t = ray_data(1,1);
rr = ray_data(1,2);
th = ray_data(1,3);

S = [t, f, 0];
P = [rr*cos(th), rr^2/(4*f), rr*sin(th)];
vi = P - S;
n = [P(1), -2*f, P(3)];
vr = vi - 2 * dot(vi,n) / dot(n,n) * n;
lambda = (screen_y_show - P(2)) / vr(2);
Q = P + lambda * vr;

text(S(1)-8, S(2)-2, S(3)-6, ...
    'S(t)', ...
    'Color','r', ...
    'FontSize',11, ...
    'FontName','Times New Roman');

text(P(1)+3, P(2)+2, P(3)+3, ...
    'P', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontName','Times New Roman');

text(Q(1)+3, Q(2)+2, Q(3)+3, ...
    'Q', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'FontName','Times New Roman');

%% 8. 绘制车灯对称轴
plot3([0,0], [0,screen_y_show+20], [0,0], ...
    'k--', ...
    'LineWidth',1.3);

text(3, 95, 5, ...
    '车灯对称轴', ...
    'FontSize',10, ...
    'FontName','Microsoft YaHei');

%% 9. 绘制坐标轴箭头
axis_len_x = 70;
axis_len_y = screen_y_show + 35;
axis_len_z = 65;

quiver3(0,0,0, axis_len_x,0,0, ...
    'Color',[0.1 0.1 0.1], ...
    'LineWidth',1.6, ...
    'MaxHeadSize',0.08);

quiver3(0,0,0, 0,axis_len_y,0, ...
    'Color',[0.1 0.1 0.1], ...
    'LineWidth',1.6, ...
    'MaxHeadSize',0.08);

quiver3(0,0,0, 0,0,axis_len_z, ...
    'Color',[0.1 0.1 0.1], ...
    'LineWidth',1.6, ...
    'MaxHeadSize',0.08);

text(axis_len_x+4, 0, 0, ...
    'x 线光源方向', ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

text(0, axis_len_y+5, 0, ...
    'y 车灯正前方', ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

text(0, 0, axis_len_z+4, ...
    'z 竖直方向', ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

%% 10. 图形美化
xlabel('x / mm', 'FontSize',12, 'FontName','Times New Roman');
ylabel('y / mm', 'FontSize',12, 'FontName','Times New Roman');
zlabel('z / mm', 'FontSize',12, 'FontName','Times New Roman');

title('一次反射光线追踪示意图', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'FontName','Microsoft YaHei');

axis equal;
xlim([-65, 75]);
ylim([-5, screen_y_show+40]);
zlim([-55, 75]);

view(38, 24);

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1.0, ...
    'GridLineStyle','--', ...
    'GridAlpha',0.25, ...
    'FontName','Times New Roman');

legend({'抛物面反光面','开口边界','焦点 F','线光源','测试屏', ...
        '入射光线','反射光线','反射点','测试屏落点','车灯对称轴'}, ...
    'Location','northeastoutside', ...
    'FontName','Microsoft YaHei', ...
    'FontSize',9);

%% 11. 保存图片
exportgraphics(gcf, '图2_一次反射光线追踪示意图.png', 'Resolution', 300);