%% 图3 测试屏最大水平覆盖范围随线光源长度变化图

clear; clc; close all;

%% 1. 基本参数
R = 36;              % 开口半径，mm
d = 21.6;            % 深度，mm
f = R^2/(4*d);       % 焦距，mm

D = 25000;           % 焦点到测试屏距离，mm

AB = 1300;           % B点到A点距离，mm
AC = 2600;           % C点到A点距离，mm

%% 2. 计算B、C点对应线光源长度
L_B = 2*f*AB/D;
L_C = 2*f*AC/D;
L_star = L_C;

fprintf('焦距 f = %.2f mm\n', f);
fprintf('B点达标长度 L_B = %.2f mm\n', L_B);
fprintf('C点达标长度 L_C = %.2f mm\n', L_C);
fprintf('最小可行线光源长度 L* = %.2f mm\n', L_star);

%% 3. 生成直线关系
L = linspace(0, 4, 300);          % 线光源长度，mm

Xmax_mm = D .* L ./ (2*f);        % 最大水平覆盖范围，mm
Xmax_m = Xmax_mm ./ 1000;         % 转换为m

%% 4. 绘图
figure('Color','w','Position',[100 100 900 600]);
hold on; grid on; box on;

p1 = plot(L, Xmax_m, ...
    'LineWidth',2.4, ...
    'DisplayName','最大水平覆盖范围 X_{max}(L)');

% B、C水平距离线
yline(AB/1000, '--', ...
    'B点位置：AB=1.3 m', ...
    'LineWidth',1.5, ...
    'FontName','Microsoft YaHei', ...
    'LabelHorizontalAlignment','left', ...
    'HandleVisibility','off');

yline(AC/1000, '--', ...
    'C点位置：AC=2.6 m', ...
    'LineWidth',1.5, ...
    'FontName','Microsoft YaHei', ...
    'LabelHorizontalAlignment','left', ...
    'HandleVisibility','off');

% B、C对应长度竖线
xline(L_B, ':', ...
    ['L_B=', num2str(L_B,'%.2f'), ' mm'], ...
    'LineWidth',1.5, ...
    'FontName','Microsoft YaHei', ...
    'LabelOrientation','aligned', ...
    'HandleVisibility','off');

xline(L_C, '-.', ...
    ['L^*=', num2str(L_C,'%.2f'), ' mm'], ...
    'LineWidth',1.8, ...
    'FontName','Microsoft YaHei', ...
    'LabelOrientation','aligned', ...
    'HandleVisibility','off');

% 交点
plot(L_B, AB/1000, 'ko', ...
    'MarkerSize',8, ...
    'MarkerFaceColor','k', ...
    'HandleVisibility','off');

plot(L_C, AC/1000, 'kp', ...
    'MarkerSize',12, ...
    'MarkerFaceColor','k', ...
    'HandleVisibility','off');

text(L_B+0.08, AB/1000+0.08, ...
    ['B达标：L=', num2str(L_B,'%.2f'), ' mm'], ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

text(L_C-0.95, AC/1000+0.12, ...
    ['C达标：L^*=', num2str(L_C,'%.2f'), ' mm'], ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

xlabel('线光源长度 L / mm', ...
    'FontSize',13, ...
    'FontName','Microsoft YaHei');

ylabel('测试屏最大水平覆盖范围 X_{max} / m', ...
    'FontSize',13, ...
    'FontName','Microsoft YaHei');

title('测试屏最大水平覆盖范围随线光源长度变化图', ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'FontName','Microsoft YaHei');

legend(p1, ...
    'Location','northwest', ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

set(gca, ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'GridLineStyle','--', ...
    'GridAlpha',0.25, ...
    'FontName','Times New Roman');

xlim([0 4]);
ylim([0 3.2]);

try
    axtoolbar(gca,'none');
catch
end

exportgraphics(gcf, ...
    '图3_测试屏最大水平覆盖范围随线光源长度变化图.png', ...
    'Resolution',300);