%% 图4 线光源所需功率随长度变化曲线
% 坐标系：
% x轴：水平方向，线光源方向
% y轴：车灯对称轴，指向正前方
% z轴：竖直方向
%
% 建模口径：
% 线光源均匀发光，单位长度功率一定，因此总功率 W 与线光源长度 L 成正比。
% 由几何覆盖关系可知，满足C点要求的最小可行长度为 L*=3.12 mm。
% 因此 L<L* 时不可行，L>=L* 时功率随 L 线性增加。

clear; clc; close all;

%% 1. 基本参数
R = 36;              % 车灯开口半径，mm
d = 21.6;            % 车灯深度，mm
f = R^2/(4*d);       % 焦距，mm

D = 25000;           % 焦点到测试屏距离，mm

AB = 1300;           % B点距A点水平距离，mm
AC = 2600;           % C点距A点水平距离，mm

% B、C点达标所需线光源长度
L_B = 2*f*AB/D;
L_C = 2*f*AC/D;
L_star = L_C;        % 最小可行长度

fprintf('焦距 f = %.2f mm\n', f);
fprintf('B点达标长度 L_B = %.2f mm\n', L_B);
fprintf('C点达标长度 L_C = %.2f mm\n', L_C);
fprintf('最小可行线光源长度 L* = %.2f mm\n', L_star);

%% 2. 设定线光源长度与归一化功率
L = linspace(0, 6, 500);     % 线光源长度，mm

% 归一化功率：令 L=L* 时，W=1
W = L / L_star;

% 不可行区间：L < L*
W_infeasible = W;
W_infeasible(L >= L_star) = NaN;

% 可行区间：L >= L*
W_feasible = W;
W_feasible(L < L_star) = NaN;

%% 3. 绘图
figure('Color','w','Position',[100 100 900 600]);
hold on; grid on; box on;

% 阴影表示不可行区域
patch([0 L_star L_star 0], ...
      [0 0 2.1 2.1], ...
      [0.90 0.90 0.90], ...
      'EdgeColor','none', ...
      'FaceAlpha',0.55, ...
      'HandleVisibility','off');

text(L_star/2-0.35, 1.85, ...
    '不可行区间', ...
    'FontSize',12, ...
    'FontName','Microsoft YaHei');

% 不可行段功率线，虚线
p1 = plot(L, W_infeasible, ...
    '--', ...
    'LineWidth',2.0, ...
    'DisplayName','未满足设计规范');

% 可行段功率线，实线
p2 = plot(L, W_feasible, ...
    '-', ...
    'LineWidth',2.4, ...
    'DisplayName','满足设计规范后的功率');

% 最小可行长度竖线
xline(L_star, '-.', ...
    ['最小可行长度 L^*=', num2str(L_star,'%.2f'), ' mm'], ...
    'LineWidth',1.8, ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei', ...
    'LabelOrientation','aligned', ...
    'HandleVisibility','off');

% B点达标长度辅助线
xline(L_B, ':', ...
    ['B点达标 L=', num2str(L_B,'%.2f'), ' mm'], ...
    'LineWidth',1.4, ...
    'FontSize',10, ...
    'FontName','Microsoft YaHei', ...
    'LabelOrientation','aligned', ...
    'HandleVisibility','off');

% 最优点
plot(L_star, 1, 'kp', ...
    'MarkerSize',13, ...
    'MarkerFaceColor','k', ...
    'MarkerEdgeColor','k', ...
    'HandleVisibility','off');

text(L_star+0.12, 1.04, ...
    ['最小功率点  (', num2str(L_star,'%.2f'), ' mm, 1)'], ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

% 归一化最小功率线
yline(1, '--', ...
    '归一化最小功率 W=1', ...
    'LineWidth',1.4, ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei', ...
    'LabelHorizontalAlignment','right', ...
    'HandleVisibility','off');

%% 4. 坐标轴和标题
xlabel('线光源长度 L / mm', ...
    'FontSize',13, ...
    'FontName','Microsoft YaHei');

ylabel('归一化功率 W / W_{min}', ...
    'FontSize',13, ...
    'FontName','Microsoft YaHei');

title('线光源所需功率随长度变化曲线', ...
    'FontSize',16, ...
    'FontWeight','bold', ...
    'FontName','Microsoft YaHei');

legend([p1 p2], ...
    'Location','northwest', ...
    'FontSize',11, ...
    'FontName','Microsoft YaHei');

set(gca, ...
    'FontSize',12, ...
    'LineWidth',1.0, ...
    'GridLineStyle','--', ...
    'GridAlpha',0.25, ...
    'FontName','Times New Roman');

xlim([0 6]);
ylim([0 2.1]);

%% 5. 去掉工具栏并保存高清图
try
    axtoolbar(gca,'none');
catch
end

exportgraphics(gcf, ...
    '图4_线光源所需功率随长度变化曲线.png', ...
    'Resolution',300);