%% 图5-2 第一问模型求解流程图
clear;
clc;
close all;

figure('Color','w','Position',[300 50 750 900]);

axis off;


%% =========================
% 流程框的位置参数
% ==========================

x = 0.20;
w = 0.60;
h = 0.085;

y1 = 0.86;
y2 = 0.72;
y3 = 0.58;
y4 = 0.44;
y5 = 0.30;
y6 = 0.16;
y7 = 0.035;


%% =========================
% 1. 输入参数
% ==========================

annotation('textbox',[x y1 w h],...
    'String',{
    '输入模型参数',...
    '\alpha，n，\Delta\sigma'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.5,...
    'BackgroundColor',[0.95 0.95 0.95],...
    'FitBoxToText','off');


%% =========================
% 2. Snell 定律
% ==========================

annotation('textbox',[x y2 w h],...
    'String',{
    '根据 Snell 定律计算折射角',...
    '\theta = asin[sin(\alpha)/n]'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.5,...
    'BackgroundColor',[0.95 0.95 1.00],...
    'FitBoxToText','off');


%% =========================
% 3. 建立光程差
% ==========================

annotation('textbox',[x y3 w h],...
    'String',{
    '建立两束反射光的光程差',...
    '\DeltaL = 2nd cos(\theta)'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.5,...
    'BackgroundColor',[0.95 1.00 0.95],...
    'FitBoxToText','off');


%% =========================
% 4. 相邻干涉极值
% ==========================

annotation('textbox',[x y4 w h],...
    'String',{
    '选取相邻两个同类型干涉极值',...
    '\Delta\sigma = \sigma_{m+1} - \sigma_m'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.5,...
    'BackgroundColor',[1.00 0.98 0.92],...
    'FitBoxToText','off');


%% =========================
% 5. 消去干涉级次
% ==========================

annotation('textbox',[x y5 w h],...
    'String',{
    '利用相邻极值干涉级次相差 1',...
    '2nd cos(\theta)\Delta\sigma = 1'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.5,...
    'BackgroundColor',[1.00 0.95 0.95],...
    'FitBoxToText','off');


%% =========================
% 6. 厚度反演
% ==========================

annotation('textbox',[x y6 w h],...
    'String',{
    '计算外延层厚度',...
    'd = 1 / [2n cos(\theta)\Delta\sigma]'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.8,...
    'BackgroundColor',[0.92 0.97 1.00],...
    'FitBoxToText','off');


%% =========================
% 7. 单位换算
% ==========================

annotation('textbox',[x y7 w h],...
    'String',{
    '单位换算并输出厚度',...
    'd_{\mum} = 10^4 d_{cm}'
    },...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'FontSize',14,...
    'LineWidth',1.5,...
    'BackgroundColor',[0.95 0.95 0.95],...
    'FitBoxToText','off');


%% =========================
% 绘制箭头
% ==========================

xc = 0.50;

annotation('arrow',[xc xc],[y1 y2+h],...
    'LineWidth',1.5);

annotation('arrow',[xc xc],[y2 y3+h],...
    'LineWidth',1.5);

annotation('arrow',[xc xc],[y3 y4+h],...
    'LineWidth',1.5);

annotation('arrow',[xc xc],[y4 y5+h],...
    'LineWidth',1.5);

annotation('arrow',[xc xc],[y5 y6+h],...
    'LineWidth',1.5);

annotation('arrow',[xc xc],[y6 y7+h],...
    'LineWidth',1.5);


%% =========================
% 标题
% ==========================

annotation('textbox',[0.12 0.955 0.76 0.035],...
    'String','图5-2  第一问外延层厚度模型求解流程图',...
    'HorizontalAlignment','center',...
    'VerticalAlignment','middle',...
    'EdgeColor','none',...
    'FontSize',16,...
    'FontWeight','normal');


%% =========================
% 保存图片
% ==========================

exportgraphics(gcf,...
    '图5-2_第一问模型求解流程图.png',...
    'Resolution',300);