%% 问题三前置分析：候选供应商集合与未来24周供货能力估计
% 主要功能：
% 1. 读取附件1中的402家供应商近5年订货量、供货量数据；
% 2. 读取问题一综合重要度和问题二供货能力参数；
% 3. 读取问题二确定的57家核心供应商集合；
% 4. 根据历史同周期供货率估计未来24周订货响应系数；
% 5. 构造"订货响应系数 + 规划供货上限"的未来供货能力参数；
% 6. 在57家核心供应商基础上，自动增加A类候选供应商；
% 7. 输出第三问候选供应商集合和24周供货能力矩阵。
%
% 重要说明：
% 本程序不是第三问最终的订购—库存—转运优化程序。
% 本程序只生成下一步优化所需的候选集合和供货能力参数。
%
% 下一步订购模型中，供应商i在第t周的预计实际供货量可设置为：
%     s(i,t) <= rho(i,t) * x(i,t)
%     s(i,t) <= Uplan(i)
% 其中：
%     x(i,t)   为订货量；
%     s(i,t)   为预计实际供货量；
%     rho(i,t) 为本程序估计的24周订货响应系数；
%     Uplan(i) 为本程序得到的规划供货上限。
%
% 必需输入文件：
% （1）附件1 近5年402家供应商的相关数据.xlsx
%      工作表：
%      - 企业的订货量（m³）
%      - 供应商的供货量（m³）
%
% （2）问题二_供应商未来供货能力分析.xlsx
%      工作表：
%      - 未来供货能力参数
%
% （3）问题二_多年度情景最少供应商选择结果.xlsx
%      工作表：
%      - 选择集合_0p0pct
%
% 主要输出文件：
% 问题三_候选供应商与未来24周供货能力估计.xlsx
% 问题三_候选集合24周典型订单产能.png
% 问题三_核心与候选集合规划上限对比.png
% 问题三_新增A类候选供应商能力排名.png

clear;
clc;
close all;

%% 1. 参数设置
numberOfSuppliers = 402;
historyWeeks = 240;
numberOfYears = 5;
weeksPerYear = 48;
futureWeeks = 24;

weeklyProductDemand = 28200;

% 历史年度时间权重：越接近当前，权重越高
yearWeights = (1:numberOfYears)';
yearWeights = yearWeights/sum(yearWeights);

% 同周期响应系数的收缩平滑参数
% 有效历史样本越少，预测结果越靠近供应商总体响应系数
shrinkageKappa = 2;

% 数值计算下限，只用于避免除以0
minimumPositiveResponse = 1e-6;

% 输入文件
originalFileDefault = '附件1 近5年402家供应商的相关数据.xlsx';
capacityFileDefault = '问题二_供应商未来供货能力分析.xlsx';
selectionFileDefault = '问题二_多年度情景最少供应商选择结果.xlsx';

% 输出文件
outputFile = '问题三_候选供应商与未来24周供货能力估计.xlsx';
figureExpectedFile = '问题三_候选集合24周典型订单产能.png';
figureUpperFile = '问题三_核心与候选集合规划上限对比.png';
figureAddedAFile = '问题三_新增A类候选供应商能力排名.png';

%% 2. 自动寻找输入文件
originalFile = localFindInputFile( ...
    originalFileDefault, ...
    '附件1 近5年402家供应商的相关数据*.xlsx', ...
    '附件1供应商历史数据文件');

capacityFile = localFindInputFile( ...
    capacityFileDefault, ...
    '问题二_供应商未来供货能力分析*.xlsx', ...
    '问题二供货能力分析文件');

selectionFile = localFindInputFile( ...
    selectionFileDefault, ...
    '问题二_多年度情景最少供应商选择结果*.xlsx', ...
    '问题二最少供应商选择结果文件');

fprintf('\n================ 输入文件 ================\n');
fprintf('历史数据文件：%s\n',originalFile);
fprintf('供货能力文件：%s\n',capacityFile);
fprintf('核心集合文件：%s\n',selectionFile);

%% 3. 读取附件1订货量与供货量
orderCell = readcell(originalFile,'Sheet','企业的订货量（m³）');
supplyCell = readcell(originalFile,'Sheet','供应商的供货量（m³）');

if size(orderCell,1) < numberOfSuppliers+1 || ...
        size(orderCell,2) < historyWeeks+2
    error('订货量工作表的行数或周数不足。');
end

if size(supplyCell,1) < numberOfSuppliers+1 || ...
        size(supplyCell,2) < historyWeeks+2
    error('供货量工作表的行数或周数不足。');
end

supplierID = strtrim(string(orderCell(2:numberOfSuppliers+1,1)));
materialType = upper(strtrim(string( ...
    orderCell(2:numberOfSuppliers+1,2))));

supplyID = strtrim(string( ...
    supplyCell(2:numberOfSuppliers+1,1)));
supplyType = upper(strtrim(string( ...
    supplyCell(2:numberOfSuppliers+1,2))));

if any(supplierID ~= supplyID)
    error('订货量表和供货量表中的供应商编号不一致。');
end

if any(materialType ~= supplyType)
    error('订货量表和供货量表中的材料类别不一致。');
end

if numel(unique(supplierID)) ~= numberOfSuppliers
    error('供应商编号存在重复或缺失。');
end

validMaterial = materialType=="A" | ...
    materialType=="B" | materialType=="C";

if any(~validMaterial)
    error('材料类别中存在A、B、C以外的内容。');
end

orderQuantity = localCellBlockToDouble( ...
    orderCell(2:numberOfSuppliers+1,3:historyWeeks+2), ...
    0, ...
    '历史订货量');

supplyQuantity = localCellBlockToDouble( ...
    supplyCell(2:numberOfSuppliers+1,3:historyWeeks+2), ...
    0, ...
    '历史供货量');

if any(orderQuantity(:)<0) || any(supplyQuantity(:)<0)
    error('历史订货量或供货量中存在负数。');
end

%% 4. 读取问题二供货能力参数
capacityCell = readcell(capacityFile,'Sheet','未来供货能力参数');
capacityHeader = strtrim(string(capacityCell(1,:)));

capacityIDColumn = localFindHeader( ...
    capacityHeader,'供应商编号');
capacityTypeColumn = localFindHeader( ...
    capacityHeader,'材料类别');
rankColumn = localFindHeader( ...
    capacityHeader,'问题一综合排名');
scoreColumn = localFindHeader( ...
    capacityHeader,'问题一综合重要度');
completionColumn = localFindHeader( ...
    capacityHeader,'订货完成率');
stableUpperColumn = localFindHeader( ...
    capacityHeader,'稳健供货上限');
overallResponseColumn = localFindHeader( ...
    capacityHeader,'订货响应系数');
typicalOrderColumn = localFindHeader( ...
    capacityHeader,'典型订货量');
timeWeightedColumn = localFindHeader( ...
    capacityHeader,'时间加权期望供货能力');
recentAbilityColumn = localFindHeader( ...
    capacityHeader,'最近一年期望供货能力');
recentRatioColumn = localFindHeader( ...
    capacityHeader,'最近一年与历史年度均值之比');

capacityID = strtrim(string( ...
    capacityCell(2:end,capacityIDColumn)));
capacityType = upper(strtrim(string( ...
    capacityCell(2:end,capacityTypeColumn))));

[parameterFound,parameterLocation] = ...
    ismember(supplierID,capacityID);

if any(~parameterFound)
    error('供货能力参数表中缺少部分供应商。');
end

if any(materialType ~= capacityType(parameterLocation))
    error('历史数据与供货能力参数表中的材料类别不一致。');
end

allRank = localCellBlockToDouble( ...
    capacityCell(2:end,rankColumn), ...
    NaN, ...
    '问题一综合排名');

allScore = localCellBlockToDouble( ...
    capacityCell(2:end,scoreColumn), ...
    NaN, ...
    '问题一综合重要度');

allCompletion = localCellBlockToDouble( ...
    capacityCell(2:end,completionColumn), ...
    0, ...
    '订货完成率');

allStableUpper = localCellBlockToDouble( ...
    capacityCell(2:end,stableUpperColumn), ...
    0, ...
    '稳健供货上限');

allOverallResponse = localCellBlockToDouble( ...
    capacityCell(2:end,overallResponseColumn), ...
    0, ...
    '订货响应系数');

allTypicalOrder = localCellBlockToDouble( ...
    capacityCell(2:end,typicalOrderColumn), ...
    0, ...
    '典型订货量');

allTimeWeightedAbility = localCellBlockToDouble( ...
    capacityCell(2:end,timeWeightedColumn), ...
    0, ...
    '时间加权期望供货能力');

allRecentAbility = localCellBlockToDouble( ...
    capacityCell(2:end,recentAbilityColumn), ...
    0, ...
    '最近一年期望供货能力');

allRecentRatio = localCellBlockToDouble( ...
    capacityCell(2:end,recentRatioColumn), ...
    NaN, ...
    '最近一年与历史年度均值之比');

problem1Rank = allRank(parameterLocation);
problem1Score = allScore(parameterLocation);
completionRate = allCompletion(parameterLocation);
stableSupplyUpper = allStableUpper(parameterLocation);
overallResponse = allOverallResponse(parameterLocation);
typicalOrder = allTypicalOrder(parameterLocation);
timeWeightedAbility = allTimeWeightedAbility(parameterLocation);
recentYearAbility = allRecentAbility(parameterLocation);
recentToHistoryRatio = allRecentRatio(parameterLocation);

if any(~isfinite(problem1Rank)) || ...
        any(~isfinite(problem1Score))
    error('问题一综合排名或综合重要度存在缺失值。');
end

%% 5. 读取问题二57家核心供应商集合
coreCell = readcell(selectionFile,'Sheet','选择集合_0p0pct');
coreHeader = strtrim(string(coreCell(1,:)));

coreIDColumn = localFindHeader(coreHeader,'供应商编号');
coreID = strtrim(string(coreCell(2:end,coreIDColumn)));
coreID = coreID(strlength(coreID)>0 & ~ismissing(coreID));

isCoreSupplier = ismember(supplierID,coreID);

if sum(isCoreSupplier) ~= numel(unique(coreID))
    error('部分核心供应商未能与402家供应商数据匹配。');
end

if sum(isCoreSupplier) ~= 57
    warning('读取到的核心供应商数量为%d家，不是预期的57家。', ...
        sum(isCoreSupplier));
end

%% 6. 原材料消耗系数与产能换算系数
materialConsumption = zeros(numberOfSuppliers,1);
materialConsumption(materialType=="A") = 0.60;
materialConsumption(materialType=="B") = 0.66;
materialConsumption(materialType=="C") = 0.72;

%% 7. 构造供应商规划供货上限
% 稳健供货上限采用正供货周供货量的90%分位数。
% 但少数供应商的时间加权期望能力可能高于该分位数。
% 为避免"期望能力高于规划上限"的内部矛盾，定义：
%
% Uplan(i) = max(稳健供货上限, 时间加权期望供货能力)
%
% Uplan用于下一步订购模型中的供货上限约束。
planningSupplyUpper = max( ...
    stableSupplyUpper,timeWeightedAbility);

planningProductUpper = ...
    planningSupplyUpper ./ materialConsumption;

%% 8. 估计未来24周订货响应系数
% 对未来第t周，参考历史：
% t, 48+t, 96+t, 144+t, 192+t
%
% 先计算对应周次的实际供货率：
% r = 实际供货量 / 订货量
%
% 对5个年度按1:2:3:4:5加权。
% 若同周期有效样本较少，则向供应商总体响应系数收缩。

futureResponse = zeros(numberOfSuppliers,futureWeeks);
samePeriodSampleCount = zeros(numberOfSuppliers,futureWeeks);
samePeriodWeightedResponse = zeros( ...
    numberOfSuppliers,futureWeeks);
responseUpper = zeros(numberOfSuppliers,1);

for i = 1:numberOfSuppliers
    validOrderWeek = orderQuantity(i,:)>0;
    historicalRatio = supplyQuantity(i,validOrderWeek) ./ ...
        orderQuantity(i,validOrderWeek);

    historicalRatio = historicalRatio( ...
        isfinite(historicalRatio) & historicalRatio>=0);

    if isempty(historicalRatio)
        responseUpper(i) = max(overallResponse(i),0);
    else
        responseUpper(i) = max( ...
            overallResponse(i), ...
            localPercentile(historicalRatio,90));
    end

    for t = 1:futureWeeks
        historicalIndex = t + ...
            weeksPerYear*(0:numberOfYears-1);

        historicalOrder = orderQuantity(i,historicalIndex);
        historicalSupply = supplyQuantity(i,historicalIndex);

        validSamePeriod = historicalOrder>0;
        sampleCount = sum(validSamePeriod);
        samePeriodSampleCount(i,t) = sampleCount;

        if sampleCount>0
            responseSample = ...
                historicalSupply(validSamePeriod) ./ ...
                historicalOrder(validSamePeriod);

            currentWeights = yearWeights(validSamePeriod);

            seasonalResponse = ...
                sum(currentWeights.*responseSample') / ...
                sum(currentWeights);
        else
            seasonalResponse = overallResponse(i);
        end

        samePeriodWeightedResponse(i,t) = seasonalResponse;

        shrinkageWeight = ...
            sampleCount/(sampleCount+shrinkageKappa);

        responseEstimate = ...
            shrinkageWeight*seasonalResponse + ...
            (1-shrinkageWeight)*overallResponse(i);

        responseEstimate = max(responseEstimate,0);

        if responseUpper(i)>0
            responseEstimate = min( ...
                responseEstimate,responseUpper(i));
        end

        futureResponse(i,t) = responseEstimate;
    end
end

%% 9. 计算典型订货量下的未来24周预计供货量
% 该矩阵只表示"按历史典型订货量下单"时的基准预计供货量，
% 不代表供应商的最大供货能力。
%
% 下一步优化时，应使用：
% s(i,t) <= futureResponse(i,t)*x(i,t)
% s(i,t) <= planningSupplyUpper(i)
typicalOrderExpectedSupply = ...
    bsxfun(@times,futureResponse,typicalOrder);

typicalOrderExpectedSupply = min( ...
    typicalOrderExpectedSupply, ...
    repmat(planningSupplyUpper,1,futureWeeks));

typicalOrderExpectedProduct = ...
    bsxfun(@rdivide, ...
    typicalOrderExpectedSupply,materialConsumption);

%% 10. 计算达到规划供货上限所需的参考订货量
referenceOrderToUpper = nan( ...
    numberOfSuppliers,futureWeeks);

for i = 1:numberOfSuppliers
    for t = 1:futureWeeks
        if futureResponse(i,t)>minimumPositiveResponse
            referenceOrderToUpper(i,t) = ...
                planningSupplyUpper(i) / ...
                futureResponse(i,t);
        end
    end
end

%% 11. 确定第三问候选供应商集合
% 候选集合构造规则：
%
% 第一部分：保留问题二得到的核心供应商；
%
% 第二部分：第三问要求尽量增加A类原材料。
% 对未进入核心集合的A类供应商，构造：
%
% 候选贡献值 =
% A类规划产能上限 × 问题一综合重要度
%
% 依次加入候选贡献值较大的A类供应商，
% 直到候选集合中A类供应商的规划产能上限
% 能够理论上覆盖企业每周28200立方米产品需求。
%
% 该条件不表示未来一定全部使用A类原材料，
% 只表示候选集合为后续优化提供了"尽可能使用A类"的选择空间。

isCandidate = isCoreSupplier;
candidateReason = strings(numberOfSuppliers,1);
candidateReason(isCoreSupplier) = "问题二57家核心供应商";

candidateContributionScore = ...
    planningProductUpper .* problem1Score;

currentAProductUpper = sum( ...
    planningProductUpper( ...
    isCandidate & materialType=="A"));

remainingA = find( ...
    ~isCandidate & ...
    materialType=="A" & ...
    planningSupplyUpper>0);

if ~isempty(remainingA)
    sortingMatrix = [ ...
        -candidateContributionScore(remainingA), ...
        problem1Rank(remainingA)];

    [~,sortingOrder] = sortrows(sortingMatrix,[1,2]);
    sortedRemainingA = remainingA(sortingOrder);
else
    sortedRemainingA = zeros(0,1);
end

for k = 1:numel(sortedRemainingA)
    if currentAProductUpper >= weeklyProductDemand
        break;
    end

    supplierIndex = sortedRemainingA(k);
    isCandidate(supplierIndex) = true;
    candidateReason(supplierIndex) = ...
        "提高A类原材料替代能力";

    currentAProductUpper = ...
        currentAProductUpper + ...
        planningProductUpper(supplierIndex);
end

% 若全部A类供应商仍不能覆盖需求，保留所有可用A类，
% 并在命令行给出提示。
if currentAProductUpper < weeklyProductDemand
    warning(['全部A类候选供应商的规划产能上限仍不能单独覆盖' ...
        '企业每周生产需求，后续模型必须使用B类或C类原材料补充。']);
end

% 进一步检查整个候选集合的规划产能上限。
% 正常情况下57家核心供应商已能满足该条件。
% 若仍不足，则先补充B类，再补充C类。
currentTotalProductUpper = sum( ...
    planningProductUpper(isCandidate));

preferredTypeList = {'B','C'};

for preferredTypeIndex = 1:numel(preferredTypeList)
    preferredType = string(preferredTypeList{preferredTypeIndex});

    if currentTotalProductUpper >= weeklyProductDemand
        break;
    end

    remainingCurrentType = find( ...
        ~isCandidate & ...
        materialType==preferredType & ...
        planningSupplyUpper>0);

    if isempty(remainingCurrentType)
        continue;
    end

    sortingMatrix = [ ...
        -candidateContributionScore(remainingCurrentType), ...
        problem1Rank(remainingCurrentType)];

    [~,sortingOrder] = sortrows(sortingMatrix,[1,2]);
    sortedRemaining = ...
        remainingCurrentType(sortingOrder);

    for k = 1:numel(sortedRemaining)
        if currentTotalProductUpper >= weeklyProductDemand
            break;
        end

        supplierIndex = sortedRemaining(k);
        isCandidate(supplierIndex) = true;

        if preferredType=="B"
            candidateReason(supplierIndex) = ...
                "补足候选集合总供货能力的B类供应商";
        else
            candidateReason(supplierIndex) = ...
                "补足候选集合总供货能力的C类供应商";
        end

        currentTotalProductUpper = ...
            currentTotalProductUpper + ...
            planningProductUpper(supplierIndex);
    end
end

if currentTotalProductUpper < weeklyProductDemand
    error('全部可用供应商的规划产能上限仍无法满足生产需求。');
end

%% 12. 候选集合关键指标
candidateIndex = find(isCandidate);
addedSupplierIndex = find(isCandidate & ~isCoreSupplier);
addedAIndex = find( ...
    isCandidate & ~isCoreSupplier & materialType=="A");

coreA = sum(isCoreSupplier & materialType=="A");
coreB = sum(isCoreSupplier & materialType=="B");
coreC = sum(isCoreSupplier & materialType=="C");

candidateA = sum(isCandidate & materialType=="A");
candidateB = sum(isCandidate & materialType=="B");
candidateC = sum(isCandidate & materialType=="C");

corePlanningUpperByType = [ ...
    sum(planningProductUpper( ...
        isCoreSupplier & materialType=="A")), ...
    sum(planningProductUpper( ...
        isCoreSupplier & materialType=="B")), ...
    sum(planningProductUpper( ...
        isCoreSupplier & materialType=="C"))];

candidatePlanningUpperByType = [ ...
    sum(planningProductUpper( ...
        isCandidate & materialType=="A")), ...
    sum(planningProductUpper( ...
        isCandidate & materialType=="B")), ...
    sum(planningProductUpper( ...
        isCandidate & materialType=="C"))];

coreTypicalProductByWeek = ...
    sum(typicalOrderExpectedProduct( ...
    isCoreSupplier,:),1);

candidateTypicalProductByWeek = ...
    sum(typicalOrderExpectedProduct( ...
    isCandidate,:),1);

candidateTypicalRawByType = zeros( ...
    futureWeeks,3);
candidateTypicalProductByType = zeros( ...
    futureWeeks,3);
candidateMeanResponseByType = nan( ...
    futureWeeks,3);

materialLabels = ["A","B","C"];

for typeIndex = 1:3
    currentMask = ...
        isCandidate & ...
        materialType==materialLabels(typeIndex);

    candidateTypicalRawByType(:,typeIndex) = ...
        sum(typicalOrderExpectedSupply( ...
        currentMask,:),1)';

    candidateTypicalProductByType(:,typeIndex) = ...
        sum(typicalOrderExpectedProduct( ...
        currentMask,:),1)';

    if any(currentMask)
        candidateMeanResponseByType(:,typeIndex) = ...
            mean(futureResponse(currentMask,:),1)';
    end
end

[minimumTypicalCapacity,weakestTypicalWeek] = ...
    min(candidateTypicalProductByWeek);

[maximumTypicalCapacity,strongestTypicalWeek] = ...
    max(candidateTypicalProductByWeek);

%% 13. 输出命令行关键结果
fprintf('\n================ 核心集合与候选集合 ================\n');
fprintf('问题二核心供应商数量：%d家\n',sum(isCoreSupplier));
fprintf('核心集合A/B/C类数量：%d/%d/%d\n', ...
    coreA,coreB,coreC);

fprintf('第三问候选供应商数量：%d家\n',sum(isCandidate));
fprintf('候选集合A/B/C类数量：%d/%d/%d\n', ...
    candidateA,candidateB,candidateC);
fprintf('新增候选供应商数量：%d家\n', ...
    numel(addedSupplierIndex));
fprintf('其中新增A类供应商：%d家\n', ...
    numel(addedAIndex));

fprintf('\n================ 规划供货上限 ================\n');
fprintf('核心集合A类规划产能上限：%.2f立方米产品/周\n', ...
    corePlanningUpperByType(1));
fprintf('候选集合A类规划产能上限：%.2f立方米产品/周\n', ...
    candidatePlanningUpperByType(1));
fprintf('候选集合A类上限覆盖率：%.4f\n', ...
    candidatePlanningUpperByType(1)/weeklyProductDemand);
fprintf('候选集合总规划产能上限：%.2f立方米产品/周\n', ...
    sum(candidatePlanningUpperByType));
fprintf('候选集合总上限覆盖率：%.4f\n', ...
    sum(candidatePlanningUpperByType)/weeklyProductDemand);

fprintf('\n================ 24周典型订单基准能力 ================\n');
fprintf('候选集合最弱周：第%d周\n',weakestTypicalWeek);
fprintf('最弱周典型订单预计产能：%.2f立方米产品/周\n', ...
    minimumTypicalCapacity);
fprintf('候选集合最强周：第%d周\n',strongestTypicalWeek);
fprintf('最强周典型订单预计产能：%.2f立方米产品/周\n', ...
    maximumTypicalCapacity);
fprintf(['注意：典型订单预计产能只反映按历史典型订货量下单的基准结果，' ...
    '不是候选集合的最大供货能力。\n']);

fprintf('\n================ 同周期样本情况 ================\n');
candidateSampleMatrixForCheck = ...
    samePeriodSampleCount(candidateIndex,:);
fprintf('候选供应商同周期有效样本数均值：%.4f个\n', ...
    mean(candidateSampleMatrixForCheck(:)));
fprintf('无同周期订货样本的候选供应商—周组合：%d个\n', ...
    sum(candidateSampleMatrixForCheck(:)==0));

%% 14. 构造候选供应商参数表
candidateMinimumResponse = ...
    min(futureResponse(candidateIndex,:),[],2);
candidateMeanResponse = ...
    mean(futureResponse(candidateIndex,:),2);
candidateMaximumResponse = ...
    max(futureResponse(candidateIndex,:),[],2);

candidateTypicalSupply24 = ...
    sum(typicalOrderExpectedSupply(candidateIndex,:),2);
candidateTypicalProduct24 = ...
    sum(typicalOrderExpectedProduct(candidateIndex,:),2);

candidateSampleMean = ...
    mean(samePeriodSampleCount(candidateIndex,:),2);
candidateZeroSampleWeeks = ...
    sum(samePeriodSampleCount(candidateIndex,:)==0,2);

candidateParameterTable = table( ...
    supplierID(candidateIndex), ...
    materialType(candidateIndex), ...
    isCoreSupplier(candidateIndex), ...
    candidateReason(candidateIndex), ...
    problem1Rank(candidateIndex), ...
    problem1Score(candidateIndex), ...
    completionRate(candidateIndex), ...
    overallResponse(candidateIndex), ...
    responseUpper(candidateIndex), ...
    candidateMinimumResponse, ...
    candidateMeanResponse, ...
    candidateMaximumResponse, ...
    stableSupplyUpper(candidateIndex), ...
    timeWeightedAbility(candidateIndex), ...
    planningSupplyUpper(candidateIndex), ...
    planningProductUpper(candidateIndex), ...
    typicalOrder(candidateIndex), ...
    candidateContributionScore(candidateIndex), ...
    recentYearAbility(candidateIndex), ...
    recentToHistoryRatio(candidateIndex), ...
    candidateTypicalSupply24, ...
    candidateTypicalProduct24, ...
    candidateSampleMean, ...
    candidateZeroSampleWeeks, ...
    'VariableNames',{ ...
    '供应商编号','材料类别','是否问题二核心供应商', ...
    '进入候选集合原因','问题一综合排名','问题一综合重要度', ...
    '订货完成率','总体订货响应系数','响应系数上限', ...
    '24周最小响应系数','24周平均响应系数', ...
    '24周最大响应系数','原稳健供货上限', ...
    '时间加权期望供货能力','规划供货上限', ...
    '规划产能上限','历史典型订货量', ...
    'A类候选贡献值','最近一年期望供货能力', ...
    '最近一年与历史年度均值之比', ...
    '24周典型订单预计供货总量', ...
    '24周典型订单预计产能总量', ...
    '同周期有效样本数均值','无同周期样本周数'});

% 候选表排序：核心供应商优先，其次按材料类别和综合排名
coreSortKey = double(~isCoreSupplier(candidateIndex));
materialSortKey = zeros(numel(candidateIndex),1);
materialSortKey(materialType(candidateIndex)=="A") = 1;
materialSortKey(materialType(candidateIndex)=="B") = 2;
materialSortKey(materialType(candidateIndex)=="C") = 3;

sortingMatrix = [ ...
    coreSortKey,materialSortKey, ...
    problem1Rank(candidateIndex)];

[~,candidateSortOrder] = ...
    sortrows(sortingMatrix,[1,2,3]);

candidateIndexSorted = ...
    candidateIndex(candidateSortOrder);
candidateParameterTable = ...
    candidateParameterTable(candidateSortOrder,:);

%% 15. 构造未来24周矩阵表
weekVariableNames = cell(1,futureWeeks);

for t = 1:futureWeeks
    weekVariableNames{t} = sprintf('第%d周',t);
end

responseMatrixTable = array2table( ...
    futureResponse(candidateIndexSorted,:), ...
    'VariableNames',weekVariableNames);

responseMatrixTable = addvars( ...
    responseMatrixTable, ...
    supplierID(candidateIndexSorted), ...
    materialType(candidateIndexSorted), ...
    'Before',1, ...
    'NewVariableNames',{'供应商编号','材料类别'});

expectedSupplyTable = array2table( ...
    typicalOrderExpectedSupply(candidateIndexSorted,:), ...
    'VariableNames',weekVariableNames);

expectedSupplyTable = addvars( ...
    expectedSupplyTable, ...
    supplierID(candidateIndexSorted), ...
    materialType(candidateIndexSorted), ...
    'Before',1, ...
    'NewVariableNames',{'供应商编号','材料类别'});

expectedProductTable = array2table( ...
    typicalOrderExpectedProduct(candidateIndexSorted,:), ...
    'VariableNames',weekVariableNames);

expectedProductTable = addvars( ...
    expectedProductTable, ...
    supplierID(candidateIndexSorted), ...
    materialType(candidateIndexSorted), ...
    'Before',1, ...
    'NewVariableNames',{'供应商编号','材料类别'});

referenceOrderTable = array2table( ...
    referenceOrderToUpper(candidateIndexSorted,:), ...
    'VariableNames',weekVariableNames);

referenceOrderTable = addvars( ...
    referenceOrderTable, ...
    supplierID(candidateIndexSorted), ...
    materialType(candidateIndexSorted), ...
    'Before',1, ...
    'NewVariableNames',{'供应商编号','材料类别'});

sampleCountTable = array2table( ...
    samePeriodSampleCount(candidateIndexSorted,:), ...
    'VariableNames',weekVariableNames);

sampleCountTable = addvars( ...
    sampleCountTable, ...
    supplierID(candidateIndexSorted), ...
    materialType(candidateIndexSorted), ...
    'Before',1, ...
    'NewVariableNames',{'供应商编号','材料类别'});

%% 16. 构造24周能力汇总表
weekNumber = (1:futureWeeks)';

summaryTable = table( ...
    weekNumber, ...
    candidateTypicalRawByType(:,1), ...
    candidateTypicalRawByType(:,2), ...
    candidateTypicalRawByType(:,3), ...
    sum(candidateTypicalRawByType,2), ...
    candidateTypicalProductByType(:,1), ...
    candidateTypicalProductByType(:,2), ...
    candidateTypicalProductByType(:,3), ...
    sum(candidateTypicalProductByType,2), ...
    coreTypicalProductByWeek', ...
    sum(candidateTypicalProductByType,2) / ...
        weeklyProductDemand, ...
    candidateMeanResponseByType(:,1), ...
    candidateMeanResponseByType(:,2), ...
    candidateMeanResponseByType(:,3), ...
    'VariableNames',{ ...
    '未来周次','A类典型订单预计供货量', ...
    'B类典型订单预计供货量', ...
    'C类典型订单预计供货量', ...
    '典型订单预计供货总量', ...
    'A类典型订单预计产能', ...
    'B类典型订单预计产能', ...
    'C类典型订单预计产能', ...
    '候选集合典型订单预计总产能', ...
    '核心集合典型订单预计总产能', ...
    '候选集合典型订单产能覆盖率', ...
    'A类平均响应系数', ...
    'B类平均响应系数', ...
    'C类平均响应系数'});

%% 17. 构造402家筛选参数表
fullParameterTable = table( ...
    supplierID,materialType,isCoreSupplier,isCandidate, ...
    candidateReason,problem1Rank,problem1Score, ...
    completionRate,overallResponse,responseUpper, ...
    stableSupplyUpper,timeWeightedAbility, ...
    planningSupplyUpper,planningProductUpper, ...
    typicalOrder,candidateContributionScore, ...
    recentYearAbility,recentToHistoryRatio, ...
    'VariableNames',{ ...
    '供应商编号','材料类别','是否问题二核心供应商', ...
    '是否进入第三问候选集合','进入候选集合原因', ...
    '问题一综合排名','问题一综合重要度', ...
    '订货完成率','总体订货响应系数','响应系数上限', ...
    '原稳健供货上限','时间加权期望供货能力', ...
    '规划供货上限','规划产能上限', ...
    '历史典型订货量','A类候选贡献值', ...
    '最近一年期望供货能力', ...
    '最近一年与历史年度均值之比'});

%% 18. 参数说明表
parameterName = [ ...
    "企业每周产品需求"; ...
    "历史供应商数量"; ...
    "历史周数"; ...
    "历史年度数量"; ...
    "每年度周数"; ...
    "未来估计周数"; ...
    "年度时间权重"; ...
    "响应系数收缩参数"; ...
    "规划供货上限定义"; ...
    "A类候选供应商增加规则"; ...
    "典型订单预计供货量含义"; ...
    "下一步优化约束"];

parameterValue = [ ...
    string(weeklyProductDemand); ...
    string(numberOfSuppliers); ...
    string(historyWeeks); ...
    string(numberOfYears); ...
    string(weeksPerYear); ...
    string(futureWeeks); ...
    strjoin(string(yearWeights'),'、'); ...
    string(shrinkageKappa); ...
    "max(稳健供货上限,时间加权期望供货能力)"; ...
    "按规划产能上限×综合重要度排序，增加至A类上限覆盖28200"; ...
    "按历史典型订货量下单时的基准预计供货量"; ...
    "s(i,t)<=rho(i,t)x(i,t)，且s(i,t)<=Uplan(i)"];

parameterTable = table( ...
    parameterName,parameterValue, ...
    'VariableNames',{'参数名称','参数取值或说明'});

%% 19. 写入Excel结果
writetable(candidateParameterTable, ...
    outputFile,'Sheet','候选供应商参数');

writetable(responseMatrixTable, ...
    outputFile,'Sheet','24周订货响应系数');

writetable(expectedSupplyTable, ...
    outputFile,'Sheet','24周典型订单预计供货');

writetable(expectedProductTable, ...
    outputFile,'Sheet','24周典型订单产能');

writetable(referenceOrderTable, ...
    outputFile,'Sheet','24周达到上限参考订货量');

writetable(sampleCountTable, ...
    outputFile,'Sheet','24周同周期样本数');

writetable(summaryTable, ...
    outputFile,'Sheet','24周能力汇总');

writetable(fullParameterTable, ...
    outputFile,'Sheet','402家筛选参数');

writetable(parameterTable, ...
    outputFile,'Sheet','参数与说明');

%% 20. 绘制候选集合24周典型订单预计产能图
fig1 = figure('Color','w','Position',[100,100,1100,680]);
ax1 = axes(fig1);
hold(ax1,'on');

plot(ax1,weekNumber, ...
    candidateTypicalProductByType(:,1), ...
    '-o','LineWidth',1.5,'MarkerSize',5);

plot(ax1,weekNumber, ...
    candidateTypicalProductByType(:,2), ...
    '-s','LineWidth',1.5,'MarkerSize',5);

plot(ax1,weekNumber, ...
    candidateTypicalProductByType(:,3), ...
    '-^','LineWidth',1.5,'MarkerSize',5);

plot(ax1,weekNumber, ...
    sum(candidateTypicalProductByType,2), ...
    '-','LineWidth',2.0);

plot(ax1,weekNumber, ...
    weeklyProductDemand*ones(futureWeeks,1), ...
    'k--','LineWidth',1.4);

set(ax1,'XTick',1:futureWeeks,'FontSize',11);
xlabel(ax1,'未来周次');
ylabel(ax1,'典型订单预计产能（立方米产品/周）');
title(ax1,'第三问候选集合未来24周典型订单预计产能', ...
    'FontSize',15);
legend(ax1,{'A类','B类','C类','候选集合总产能', ...
    '企业每周生产需求'}, ...
    'Location','best');
grid(ax1,'on');
hold(ax1,'off');

localCloseToolbar(ax1);
drawnow;
localExportFigure(fig1,figureExpectedFile);

%% 21. 绘制核心集合与候选集合规划上限对比图
fig2 = figure('Color','w','Position',[100,100,950,650]);
ax2 = axes(fig2);

upperComparison = [ ...
    corePlanningUpperByType; ...
    candidatePlanningUpperByType];

bar(ax2,upperComparison);

set(ax2, ...
    'XTick',1:2, ...
    'XTickLabel',{'问题二核心集合','第三问候选集合'}, ...
    'FontSize',11);

ylabel(ax2,'规划产能上限（立方米产品/周）');
title(ax2,'核心集合与第三问候选集合规划产能上限对比', ...
    'FontSize',15);
legend(ax2,{'A类','B类','C类'},'Location','best');
grid(ax2,'on');

localCloseToolbar(ax2);
drawnow;
localExportFigure(fig2,figureUpperFile);

%% 22. 绘制新增A类候选供应商能力排名图
if ~isempty(addedAIndex)
    [~,addedASort] = sort( ...
        candidateContributionScore(addedAIndex), ...
        'descend');

    addedASorted = addedAIndex(addedASort);

    fig3 = figure('Color','w','Position',[100,100,1200,700]);
    ax3 = axes(fig3);

    bar(ax3,planningProductUpper(addedASorted));

    set(ax3, ...
        'XTick',1:numel(addedASorted), ...
        'XTickLabel',cellstr(supplierID(addedASorted)), ...
        'FontSize',10);

    xtickangle(ax3,45);
    xlabel(ax3,'新增A类候选供应商');
    ylabel(ax3,'规划产能上限（立方米产品/周）');
    title(ax3,'新增A类候选供应商规划产能上限', ...
        'FontSize',15);
    grid(ax3,'on');

    localCloseToolbar(ax3);
    drawnow;
    localExportFigure(fig3,figureAddedAFile);
end

%% 23. 完成提示
fprintf('\n计算完成。\n');
fprintf('结果文件：%s\n',outputFile);
fprintf('24周典型订单产能图：%s\n',figureExpectedFile);
fprintf('核心与候选集合上限对比图：%s\n',figureUpperFile);

if ~isempty(addedAIndex)
    fprintf('新增A类候选供应商能力图：%s\n',figureAddedAFile);
end

fprintf(['下一步应读取"候选供应商参数""24周订货响应系数"' ...
    '和"24周达到上限参考订货量"，建立24周订购—库存优化模型。\n']);

%% 局部函数1：自动寻找输入文件
function fileName = localFindInputFile( ...
        defaultName,pattern,description)

    if isfile(defaultName)
        fileName = defaultName;
        return;
    end

    candidates = dir(pattern);

    if isempty(candidates)
        error('未找到%s。',description);
    end

    [~,latestIndex] = max([candidates.datenum]);
    fileName = candidates(latestIndex).name;

    fprintf('未找到默认文件名，已自动使用：%s\n',fileName);
end

%% 局部函数2：查找表头
function columnIndex = localFindHeader( ...
        headerRow,targetName)

    columnIndex = find( ...
        headerRow==string(targetName),1);

    if isempty(columnIndex)
        error('未找到列：%s',targetName);
    end
end

%% 局部函数3：混合单元格转换为数值矩阵
function numericMatrix = localCellBlockToDouble( ...
        cellBlock,blankValue,blockName)

    numericMatrix = zeros(size(cellBlock));

    for index = 1:numel(cellBlock)
        value = cellBlock{index};

        if isempty(value)
            numericMatrix(index) = blankValue;

        elseif isnumeric(value)
            if isnan(value)
                numericMatrix(index) = blankValue;
            else
                numericMatrix(index) = double(value);
            end

        elseif islogical(value)
            numericMatrix(index) = double(value);

        else
            textValue = strtrim(string(value));

            if ismissing(textValue) || ...
                    strlength(textValue)==0
                numericMatrix(index) = blankValue;
            else
                convertedValue = str2double(textValue);

                if isnan(convertedValue)
                    error('%s中存在无法转换为数值的内容：%s', ...
                        blockName,textValue);
                end

                numericMatrix(index) = convertedValue;
            end
        end
    end
end

%% 局部函数4：计算百分位数，不依赖Statistics Toolbox
function percentileValue = localPercentile( ...
        dataVector,percentileLevel)

    dataVector = dataVector(:);
    dataVector = dataVector(isfinite(dataVector));
    dataVector = sort(dataVector);

    if isempty(dataVector)
        percentileValue = NaN;
        return;
    end

    if numel(dataVector)==1
        percentileValue = dataVector(1);
        return;
    end

    percentileLevel = min( ...
        max(percentileLevel,0),100);

    position = 1 + ...
        (numel(dataVector)-1)* ...
        percentileLevel/100;

    lowerIndex = floor(position);
    upperIndex = ceil(position);

    if lowerIndex==upperIndex
        percentileValue = dataVector(lowerIndex);
    else
        interpolationWeight = ...
            position-lowerIndex;

        percentileValue = ...
            dataVector(lowerIndex) + ...
            interpolationWeight* ...
            (dataVector(upperIndex)- ...
            dataVector(lowerIndex));
    end
end

%% 局部函数5：关闭坐标区工具栏
function localCloseToolbar(ax)
    try
        if ~isempty(ax.Toolbar)
            ax.Toolbar.Visible = 'off';
        end
    catch
    end

    try
        disableDefaultInteractivity(ax);
    catch
    end
end

%% 局部函数6：导出图像
function localExportFigure(fig,fileName)
    try
        exportgraphics(fig,fileName,'Resolution',300);
    catch
        print(fig,fileName,'-dpng','-r300');
    end
end
